// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd3mrs8GmosJFeQldNcCwH3P3IBBs3eZM',
    appId: '1:666086626460:web:408d85009ce91046870959',
    messagingSenderId: '666086626460',
    projectId: 'fir-3-3a769',
    authDomain: 'fir-3-3a769.firebaseapp.com',
    storageBucket: 'fir-3-3a769.appspot.com',
    measurementId: 'G-Z2F6VQD2LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkdbKzk82LTBwzjAbpDtTkYZFE0x6Gxl8',
    appId: '1:666086626460:android:aff5dfa277615dbf870959',
    messagingSenderId: '666086626460',
    projectId: 'fir-3-3a769',
    storageBucket: 'fir-3-3a769.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxQGFKMwuxp6HpuLlcWeFBYC9MQupKB-s',
    appId: '1:666086626460:ios:a0d6261f10b42d94870959',
    messagingSenderId: '666086626460',
    projectId: 'fir-3-3a769',
    storageBucket: 'fir-3-3a769.appspot.com',
    iosBundleId: 'com.example.ishipprj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxQGFKMwuxp6HpuLlcWeFBYC9MQupKB-s',
    appId: '1:666086626460:ios:a0d6261f10b42d94870959',
    messagingSenderId: '666086626460',
    projectId: 'fir-3-3a769',
    storageBucket: 'fir-3-3a769.appspot.com',
    iosBundleId: 'com.example.ishipprj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd3mrs8GmosJFeQldNcCwH3P3IBBs3eZM',
    appId: '1:666086626460:web:9d249bfe998168f2870959',
    messagingSenderId: '666086626460',
    projectId: 'fir-3-3a769',
    authDomain: 'fir-3-3a769.firebaseapp.com',
    storageBucket: 'fir-3-3a769.appspot.com',
    measurementId: 'G-W4SY702S6B',
  );
}
